### ISSUE TITLE
Update Contact page with social media handles and email

### ISSUE THREAD

**Issue by spchal** [GayathriVihayas/C20#1]
![image](https://user-images.githubusercontent.com/1622479/231411530-f290087e-410c-4779-ac25-390d8f207500.png)

Email: tst.c20chair@amrita.edu
Instagram - https://www.instagram.com/c20techsecuritytransparency/
LinkedIn - https://www.linkedin.com/company/c20-technology-security-transparency
Twitter - https://twitter.com/c20tech
TST Website - https://c20.amma.org/technology-security-and-transparency/

**Comment by GayathriVihayas** [comment]
updated the social media handles in footer section

**Comment by spchal** [comment]
Wrong link for emai: 
![image](https://user-images.githubusercontent.com/1622479/231449871-6b4d1e07-3ae5-4968-97bb-d2cf623e6a3f.png)
It should be 
mailto:tst.c20chair@amrita.edu

**Comment by GayathriVihayas** [comment]
<img width="659" alt="Screenshot 2023-04-12 at 4 13 18 PM" src="https://user-images.githubusercontent.com/92051039/231453627-2c25da22-2126-486c-954e-c0b208725c3e.png">

**Comment by GayathriVihayas** [comment]
I put the same link u have provided

**Comment by GayathriVihayas** [comment]
please provide the address also

**Comment by spchal** [comment]
It is an email address. not a website link. https://www.wikihow.com/Create-an-Email-Link-in-HTML

**Comment by GayathriVihayas** [comment]
updated

**Comment by spchal** [comment]
One last comment: Leave the subject empty on the email. It is currently 'HTML link' 
![image](https://user-images.githubusercontent.com/1622479/231521513-ee65f028-e251-476f-a21c-b42e8f8f21d9.png)

**Comment by GayathriVihayas** [comment]
updated
