### ISSUE TITLE
Update Footer section

### ISSUE THREAD

**Issue by spchal** [GayathriVihayas/C20#2]
![image](https://user-images.githubusercontent.com/1622479/231411999-e872aeb0-eb6a-4409-81e6-f7b8b65ae509.png)
Remove the crossed sections in the image. for the rest, add the proper links as below:

News - https://c20.amma.org/news/tst/
Events - https://c20.amma.org/tst-wg/events-tst/

**Comment by GayathriVihayas** [comment]
new footer updated
