### ISSUE TITLE
Move join in person to the top

### ISSUE THREAD

**Issue by spchal** [GayathriVihayas/C20#4]
This Join in person section should be above the 'Working Group Sub themes'
![image](https://user-images.githubusercontent.com/1622479/231448281-af1dc82e-be6b-48a4-9515-a9f3675977be.png)

Also, make the video section small. The text can come on the side of the video : 
![image](https://user-images.githubusercontent.com/1622479/231449305-b1d54891-ed9c-49c4-8797-9efde7c3ded9.png)

**Comment by GayathriVihayas** [comment]
<img width="1436" alt="Screenshot 2023-04-12 at 4 35 05 PM" src="https://user-images.githubusercontent.com/92051039/231459298-6d0f59d2-2739-4482-92d8-f195f38933fa.png">
like this?

**Comment by spchal** [comment]
no, side by side. video can be made small in size, and text can come on the side so that it doesnt take so much space

**Comment by GayathriVihayas** [comment]
done
